import { renderMascot } from "./mascot";

console.log('This site was generated by Hugo with Typescript.');

const mascots = document.querySelectorAll(".mascot");
mascots.forEach(mascot => {
  if (mascot instanceof HTMLDivElement) {
    renderMascot(mascot);
  }
})

const pictures = document.querySelectorAll('picture[data-modal]');
pictures.forEach(picture => {
  if (!(picture instanceof HTMLPictureElement)) {
    return;
  }

  const modalId = picture.dataset.modal;

  if (modalId) {
    const modal = document.getElementById(modalId);
    if (modal && modal instanceof HTMLDialogElement) {
      modal.addEventListener('click', (e) => {
        if (e.target === modal) {
          modal.close();
        }
      })

      picture.addEventListener('click', () => {
        modal?.showModal();
      });
    };
  }
});
