import { renderMascot } from "./mascot";

console.log('This site was generated by Hugo with Typescript.');

const mascots = document.querySelectorAll(".mascot");
mascots.forEach(mascot => {
  if (mascot instanceof HTMLDivElement) {
    renderMascot(mascot);
  }
})
